### ISSUE TITLE
No modifications are allowed to a locked ParameterMap

### ISSUE THREAD

**Issue by barabaka** [paultuckey/urlrewritefilter#216]
Hi, I am getting the following exception in Tomcat 8.5.15 and urlrewritefilter-4.0.3.jar

java.lang.IllegalStateException: No modifications are allowed to a locked ParameterMap
	at org.apache.catalina.util.ParameterMap.checkLocked(ParameterMap.java:175)
	at org.apache.catalina.util.ParameterMap.putAll(ParameterMap.java:156)
	at org.tuckey.web.filters.urlrewrite.UrlRewriteWrappedRequest.getParameterMap(UrlRewriteWrappedRequest.java:79)

**Comment by barabaka** [comment]
Sorry, my fault, was using the old version.
