### ISSUE TITLE
Getting java.lang.OutOfMemoryError: java heap space

### ISSUE THREAD

**Issue by mrgrenier** [paultuckey/urlrewritefilter#217]
During a White Hat scan we've been getting java out of memory errors.  As a result it can bring the website down
```
Exception in thread "http-bio-8443-exec-63" java.lang.OutOfMemoryError: Java heap space
	at java.lang.StringCoding$StringEncoder.encode(StringCoding.java:300)
	at java.lang.StringCoding.encode(StringCoding.java:344)
	at java.lang.String.getBytes(String.java:916)
	at java.io.UnixFileSystem.getBooleanAttributes0(Native Method)
	at java.io.UnixFileSystem.getBooleanAttributes(UnixFileSystem.java:242)
	at java.io.File.exists(File.java:813)
	at org.apache.naming.resources.FileDirContext.file(FileDirContext.java:768)
	at org.apache.naming.resources.FileDirContext.doGetAttributes(FileDirContext.java:400)
	at org.apache.naming.resources.BaseDirContext.getAttributes(BaseDirContext.java:1139)
	at org.apache.naming.resources.BaseDirContext.getAttributes(BaseDirContext.java:1092)
	at org.apache.naming.resources.ProxyDirContext.cacheLoad(ProxyDirContext.java:1613)
	at org.apache.naming.resources.ProxyDirContext.cacheLookup(ProxyDirContext.java:1536)
	at org.apache.naming.resources.ProxyDirContext.lookup(ProxyDirContext.java:297)
	at org.apache.tomcat.util.http.mapper.Mapper.internalMapWrapper(Mapper.java:1009)
	at org.apache.tomcat.util.http.mapper.Mapper.map(Mapper.java:704)
	at org.apache.catalina.core.ApplicationContext.getRequestDispatcher(ApplicationContext.java:475)
	at org.apache.catalina.core.ApplicationContextFacade.getRequestDispatcher(ApplicationContextFacade.java:223)
	at org.apache.catalina.core.ApplicationHttpRequest.getRequestDispatcher(ApplicationHttpRequest.java:329)
	at org.tuckey.web.filters.urlrewrite.NormalRewrittenUrl.getRequestDispatcher(NormalRewrittenUrl.java:289)
	at org.tuckey.web.filters.urlrewrite.NormalRewrittenUrl.doRewrite(NormalRewrittenUrl.java:212)
	at org.tuckey.web.filters.urlrewrite.RuleChain.handleRewrite(RuleChain.java:171)
	at org.tuckey.web.filters.urlrewrite.RuleChain.doRules(RuleChain.java:145)
	at org.tuckey.web.filters.urlrewrite.UrlRewriter.processRequest(UrlRewriter.java:92)
	at org.tuckey.web.filters.urlrewrite.UrlRewriteFilter.doFilter(UrlRewriteFilter.java:389)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:243)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:210)
	at org.apache.catalina.core.ApplicationDispatcher.invoke(ApplicationDispatcher.java:749)
	at org.apache.catalina.core.ApplicationDispatcher.processRequest(ApplicationDispatcher.java:487)
	at org.apache.catalina.core.ApplicationDispatcher.doForward(ApplicationDispatcher.java:412)
	at org.apache.catalina.core.ApplicationDispatcher.forward(ApplicationDispatcher.java:339)
	at org.tuckey.web.filters.urlrewrite.NormalRewrittenUrl.doRewrite(NormalRewrittenUrl.java:213)
	at org.tuckey.web.filters.urlrewrite.RuleChain.handleRewrite(RuleChain.java:171)
```

**Comment by paultuckey** [comment]
It looks like the trace includes recursion, the stack shows this:

```
NormalRewrittenUrl.doRewrite:213     → rq.forward(...)
  ApplicationDispatcher.forward
    ApplicationFilterChain
      UrlRewriteFilter.doFilter:389  → filter runs again on the FORWARD dispatch
        UrlRewriter.processRequest:92
          RuleChain.doRules:145 → handleRewrite:171
            NormalRewrittenUrl.doRewrite:212 → forward again...
```

This is likely a config issue. 

If you believe it's not config issue can you please provide the `urlrewrite.xml`, and the filter-mapping block from `web.xml` please?

Also worth checking if `/rewrite-status` shows a rule with a to that its own from would match.
