### ISSUE TITLE
Issue with JDK11 and Apache Tomcat 10

### ISSUE THREAD

**Issue by drveresh** [paultuckey/urlrewritefilter#239]
Hi,

My servlet application is unable to get deployed due to the below error.  It was working fine with JDK8 and Apache Tomcat 8.

--------------- /apache-tomcat-10/logs/localhost.2020-11-17.log ----------------
```
17-Nov-2020 09:39:43.241 SEVERE [main] org.apache.catalina.core.StandardContext.filterStart Exception starting filter [UrlRewriteFilter]
	java.lang.ClassCastException: class org.tuckey.web.filters.urlrewrite.UrlRewriteFilter cannot be cast to class jakarta.servlet.Filter (org.tuckey.web.filters.urlrewrite.UrlRewriteFilter is in unnamed module of loader org.apache.catalina.loader.ParallelWebappClassLoader @1b73be9f; jakarta.servlet.Filter is in unnamed module of loader java.net.URLClassLoader @5f9d02cb)
		at org.apache.catalina.core.ApplicationFilterConfig.getFilter(ApplicationFilterConfig.java:250)
		at org.apache.catalina.core.ApplicationFilterConfig.<init>(ApplicationFilterConfig.java:103)
		at org.apache.catalina.core.StandardContext.filterStart(StandardContext.java:4515)
		at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5152)
		at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
		at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:717)
```

Please help me out.

**Comment by marco-brandizi** [comment]
I've just met the same problem with the latest version of the Jetty plug-in. Presumably, the problem is that web container developers have decided to move the `javax.*` namespace to the `jakarta.*` namespace (which breaks tons of packages, many thanks!!!), details [here](https://webtide.com/renaming-from-javax-to-jakarta/).

What it happens, I believe, is that Tomcat or Jetty see the `UrlRewriteFilter` in `web.xml` and then they try to verify that the configured filter implements the right interface, which isn't javax.servlet.Filter anymore.

I think it can be fixed by adding "implements jakarta.servlet.Filter" to the current declaration. The two interfaces should be identical, apart from the namespace.

**Comment by paultuckey** [comment]
I'm unfortunately not in a position to do development on this right now.  I'm happy to accept a pull-request though.

**Comment by jetztgradnet** [comment]
Any further work on this issue? Anything we can do to help?
Apparently, there was a problem with the provided PR #242, but the error log is no longer available...
With many projects now making the switch to JakartaEE having this variant would be greatly desirable. Alternatively, we need to migrate to another solution which I would like to avoid, as the Tuckey URLRewriteFilter has all we need...

**Comment by jetztgradnet** [comment]
Great, thanks, @paultuckey! Would you mind releasing this as a new version in Maven Central as well so we can make use of this in our softwre?

**Comment by paultuckey** [comment]
Hi @jetztgradnet, I got your multiple messages via email, linkedin and here.  I would like to help however I don't have a lot of spare time due to family, my paying job etc.

In recent years the container tests (in `/container-test`) for the library non longer run.  I would like to upgrade these so they actually verify the release before submitting it to maven central.

I have started this work here: https://github.com/paultuckey/urlrewritefilter/pull/248

If you have any time to help it would be appreciated.

**Comment by jetztgradnet** [comment]
Hi @paultuckey, sorry for trying different ways to reach you and thanks for getting back to me! I totally understand that you do not have too much time to spend here and very much appreciate all your work on this project and putting out a new release after completing this change.

I will help trying to get those tests running again.

**Comment by paultuckey** [comment]
I'm also working on upgrading maven dependencies: https://github.com/paultuckey/urlrewritefilter/pull/249
