### ISSUE TITLE
Bad Formed Regex - Lookbehind

### ISSUE THREAD

**Issue by GoogleCodeExporter** [paultuckey/urlrewritefilter#68]
```
What steps will reproduce the problem?
1. Put a lookbehind regex in urlrewrite.xml
2. Start application 

What is the expected output? What do you see instead?
The application starts with erros and regex doesnt work fine.

What version of the product are you using? On what operating system?
URL Rewriter: 3.2 or 2.6
OS: Windows 7
Spring 3.0
Spring Web Flow: 2.0.8 
Server: Tomcat 6

Please provide any additional information below.

Regex used: .*(?<!\.jsp)

Rule:

<rule>
<note>Redirecionamento Para Dispacther</note>
<from>^.*(?<!.jsp)$</from>
<run class="com.test.spring.DispatcherServlet" method="doService" />
</rule>

Exeception:

SEVERE: org.tuckey.web.filters.urlrewrite.Conf ERROR: Parse error on line
16 The content of elements must consist of well-formed character data or
markup.
org.xml.sax.SAXParseException: The content of elements must consist of
well-formed character data or markup.
    at com.sun.org.apache.xerces.internal.parsers.DOMParser.parse(Unknown Source)
    at
com.sun.org.apache.xerces.internal.jaxp.DocumentBuilderImpl.parse(Unknown
Source)
    at javax.xml.parsers.DocumentBuilder.parse(Unknown Source)
    at org.tuckey.web.filters.urlrewrite.Conf.loadDom(Conf.java:125)
    at org.tuckey.web.filters.urlrewrite.Conf.<init>(Conf.java:78)
    at
org.tuckey.web.filters.urlrewrite.UrlRewriteFilter.loadConf(UrlRewriteFilter.jav
a:631)


```

Original issue reported on code.google.com by `marcos.l...@gmail.com` on 3 Apr 2010 at 1:40

**Comment by paultuckey** [comment]
Stale.
